### ISSUE TITLE
RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:51

### ISSUE THREAD

**Issue by Oldes** [xinntao/ESRGAN#28]
Hi, I installed CUDAv10 on Windows 10, but I'm not able to run the test script:
```
x:\GIT\ESRGAN>python test.py models/RRDB_ESRGAN_x4.pth
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = model.to(device)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\cuda\__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:51
```

Any idea why? (maybe using LSD instead? ;-)

**Comment by Oldes** [comment]
I tried to uninstall `torch` with CUDA, and installed the CPU only one, but looks, that it is messed-up anyway:
```
x:\GIT\ESRGAN>pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: torch==1.0.0 from https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-win_amd64.w
hl in x:\utils\python37\lib\site-packages (1.0.0)

x:\GIT\ESRGAN>pip3 install torchvision
Requirement already satisfied: torchvision in x:\utils\python37\lib\site-packages (0.2.1)
Requirement already satisfied: pillow>=4.1.1 in x:\utils\python37\lib\site-packages (from torchvision) (5.4.1)
Requirement already satisfied: six in x:\utils\python37\lib\site-packages (from torchvision) (1.12.0)
Requirement already satisfied: numpy in x:\utils\python37\lib\site-packages (from torchvision) (1.16.0)
Requirement already satisfied: torch in x:\utils\python37\lib\site-packages (from torchvision) (1.0.0)

x:\GIT\ESRGAN>python test.py models/RRDB_ESRGAN_x4.pth
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = model.to(device)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\nn\modules\module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "c:\DEV\Utils\Python37\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Is the CUDA required?

**Comment by Oldes** [comment]
I installed CUDA v 9.2, reinstalled Python using Anaconda, but the error is still same:/

**Comment by xinntao** [comment]
You can do a simple test:
```
python
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.is_available())
```
to see whether the outputs are OK.

**Comment by Oldes** [comment]
I may have it mess up again... as I was trying to test it at least with CPU only (found that I must switch it manually in the `test.py` file, but this is what I have at this moment:
```
(base) X:\GIT\ESRGAN>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.0
>>> print(torch.version.cuda)
10.0
>>> print(torch.backends.cudnn.version())
7401
>>> print(torch.cuda.is_available())
False
```

**Comment by Oldes** [comment]
It looks I don't have `nvidia-smi`. Should it be part of the [CUDA toolkit](https://developer.nvidia.com/accelerated-computing-toolkit)?

**Comment by xinntao** [comment]
In Ubuntu, if you have installed Nvidia driver, there will be `nvidia-smi`. I do not know what is the case in Windows. I think your problem may be from the Nvidia driver.

**Comment by Oldes** [comment]
Hm... it looks that my Nvidia drivers disappeared when I was re-installing CUDA (from version 10 to 9.2) I'm going to install them now.

**Comment by Oldes** [comment]
OK. It works now... don't know why it happened, but I installed the latest nVidia drivers and problem solved.
@xinntao thank you!
